### ISSUE TITLE
Fail to execute tox with this plugin

### ISSUE THREAD

**Issue by Czaki** [tox-dev/tox-uv#1]
I tried to test this plugin, and it ends with:

```
Traceback (most recent call last):
  File "/Users/grzegorzbokota/.pyenv/versions/napari/bin/tox", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/run.py", line 20, in run
    result = main(sys.argv[1:] if args is None else args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/run.py", line 46, in main
    return handler(state)
           ^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/session/cmd/run/sequential.py", line 25, in run_sequential
    return execute(state, max_workers=1, has_spinner=False, live=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/session/cmd/run/common.py", line 237, in execute
    state.envs.ensure_only_run_env_is_active()
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/session/env_select.py", line 416, in ensure_only_run_env_is_active
    envs, active = self._defined_envs, self._env_name_to_active()
                   ^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/session/env_select.py", line 273, in _defined_envs
    raise failed[next(iter(failed_to_create))]
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/session/env_select.py", line 250, in _defined_envs
    run_env.package_env = self._build_pkg_env(pkg_name_type, name, env_name_to_active)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/session/env_select.py", line 321, in _build_pkg_env
    name_type = next(child_package_envs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 173, in register_run_env
    yield from super().register_run_env(run_env)
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/tox_env/python/package.py", line 117, in register_run_env
    pkg_env = run_env.conf["wheel_build_env"]
              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/config/sets.py", line 118, in __getitem__
    return self.load(item)
           ^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/config/sets.py", line 129, in load
    return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))  # noqa: PLC2801
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/config/of_type.py", line 106, in __call__
    value = self.default(conf, args.env_name) if callable(self.default) else self.default
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/tox_env/python/package.py", line 109, in default_wheel_tag
    return f"{self.conf.name}-{run_py.impl_lower}{run_py.version_no_dot}"
                               ^^^^^^^^^^^^^^^^^
  File "/Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/lib/python3.11/site-packages/tox/tox_env/python/api.py", line 44, in impl_lower
    return self.implementation.lower()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no
```

tox in version 4.12.1
System macOS
python 3.11.4 
version tox-uv 1.0.1

**Comment by Czaki** [comment]
comand: `tox run -e py311-macos-pyqt5-no_cov -n`
project https://github.com/napari/napari/

but when checking I found that I specified to use wheel build 

```
[testenv]
package = wheel
```

because of crash of uv with sdist 

https://github.com/astral-sh/uv/issues/1484#issuecomment-1948863469

Same crash here

```
py311-macos-pyqt5-no_cov: install_package> /Users/grzegorzbokota/.pyenv/versions/3.11.4/envs/napari/bin/uv pip install --reinstall --no-deps napari@/tmp/.tox/.tmp/package/11/napari-0.5.0a2.dev578+g17b00de2.tar.gz
⠹ Resolving dependencies...                                                                              thread 'main' panicked at crates/uv-resolver/src/resolution.rs:120:26:
Every package should have metadata
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So it looks like `package=wheel` makes a problem.

**Comment by gaborbernat** [comment]
> So it looks like `package=wheel` makes a problem.

Not really, this project iself is using wheel https://github.com/tox-dev/tox-uv/blob/main/tox.ini#L17 and it works https://github.com/tox-dev/tox-uv/actions/runs/7933552228/job/21662569284. 

sdist not working is likely a bug with uv.

**Comment by Czaki** [comment]
It was part of the justification why changes are required.

**Comment by Czaki** [comment]
@gaborbernat it may be bug in tox. `Every package should have metadata` 

When I pass a path to sdist using `--installpkg` it works. Could you please point me how to prevent tox form removing `sdist`?

**Comment by gaborbernat** [comment]
I don't think we do so should be available in `.tox/.pkg/tmp`.

**Comment by Czaki** [comment]
It is somehow cleaned. I have checked the path reported in the log (for example `/tmp/.tox/.tmp/package/20/`) and it is empty.

**Comment by gaborbernat** [comment]
You would need to put breakpoints in tox then, but did you try pyproject-build generates something that uv accepts?

**Comment by Czaki** [comment]
> but did you try pyproject-build generates something that uv accepts

I'm not sure what is pyproject-build but if I pass either sdist or wheel generated using `python -m build` to tox using `--installpkg` it works without any problem. This is why I expect that it may be a problem with the way how sdist is build.

**Comment by Czaki** [comment]
looks working. 
When I see workflow I see annotation that on Windows is not working. Plugin is not working or only tests?

**Comment by gaborbernat** [comment]
@Czaki seems the sdist is a tox bug... removing `toxworkdir={env:TOX_WORK_DIR:/tmp/.tox}` from your config makes it run past it...

**Comment by gaborbernat** [comment]
> When I see workflow I see annotation that on Windows is not working.

Without https://github.com/astral-sh/uv/issues/1521 uv cannot discover Python versions on Github Actions. Upstream limitation for now that I cannot enable Windows in CI. Should work once that's fixed, though.

**Comment by Czaki** [comment]
hm. Maybe I spot a different bug then: 

```
py311-windows-pyqt6-no_cov: install_package> python -I -m uv pip install --force-reinstall --no-deps "napari @ D:\a\napari\napari\dist\napari-0.5.0a2.dev560+g2c217efd-py3-none-any.whl"
error: Unable to extract filename from URL: d:\a\napari\napari\dist\napari-0.5.0a2.dev560+g2c217efd-py3-none-any.whl
```
Did you meet this earlier or should I investigate it more and maybe report to uv?

(it comes from my approach to do same as here (https://github.com/czaki/tox-uv))

**Comment by gaborbernat** [comment]
> Did you meet this earlier or should I investigate it more and maybe report to uv?

The extra spaces around ` @ ` looks suspicious, but the error is coming from uv, so I gather the error is in theri code too.

**Comment by Czaki** [comment]
Extra spaces come from my code. Because I have followed this suggestion https://github.com/astral-sh/uv/issues/1484#issuecomment-1948798461 which contains space. It works on linux and macos

**Comment by gaborbernat** [comment]
Ah, works without it too for me 😊 see https://github.com/tox-dev/tox-uv/blob/main/src/tox_uv/_installer.py#L80

**Comment by Czaki** [comment]
As I check you use uv from tox env and I have installed it in created env 

https://github.com/Czaki/tox-uv/blob/6af0f3bd7bd74094815ae701002b7f9d5ddb552e/src/tox_uv/plugin.py#L128-L137 

But also I do not use uv to create venv in such a scenario. 

This is why I do not meet problems with the discovery python version. But if the bug with paths will be solved and searching py not then it may be a good solution.
