### ISSUE TITLE
PyPy: ModuleNotFoundError: No module named 'hatchling'

### ISSUE THREAD

**Issue by hugovk** [tox-dev/tox-uv#15]
macOS, Ubuntu
(Windows has another problem: https://github.com/astral-sh/uv/issues/1636)
PyPy 3.9 - 3.10
uv 0.1.4
tox-uv 1.2.0

Using tox-uv, and running `python -m tox -e py -vvv` gives an error:

```
.pkg: 2233 I exit 0 (0.26 seconds) /home/runner/work/termcolor/termcolor> /opt/hostedtoolcache/PyPy/3.10.13/x64/bin/uv pip install hatch-vcs hatchling pid=1805 [tox/execute/api.py:280]
.pkg: 2235 W _optional_hooks> python /opt/hostedtoolcache/PyPy/3.10.13/x64/lib/pypy3.10/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
py: 2281 E packaging backend failed (code=-5), with FailedToStart: could not start backend
```

https://github.com/hugovk/termcolor/actions/runs/7948209687/job/21697973981

It passes with CPython 3.8-3.13.

To get the code locally:

```sh
git clone https://github.com/hugovk/termcolor/
git checkout 4a84c280ce5b3ddbe923b19416d3ed6df6edabe2
```

Locally on macOS (using pypy from pyenv) I get:

```pytb
❯ python --version
Python 3.10.13 (fc59e61cfbff, Jan 14 2024, 13:00:21)
[PyPy 7.3.15 with GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)]

❯ python -m tox -e py -vvv
ROOT: 198 D setup logging to NOTSET on pid 86395 [tox/report.py:221]
py: 500 W venv> /Users/hugo/.pyenv/versions/pypy3.10-7.3.15/bin/uv venv -p 3.10 /Users/hugo/github/termcolor/.tox/py/.venv [tox/tox_env/api.py:427]
py: 538 I exit 0 (0.04 seconds) /Users/hugo/github/termcolor> /Users/hugo/.pyenv/versions/pypy3.10-7.3.15/bin/uv venv -p 3.10 /Users/hugo/github/termcolor/.tox/py/.venv pid=86446 [tox/execute/api.py:280]
.pkg: 545 W venv> /Users/hugo/.pyenv/versions/pypy3.10-7.3.15/bin/uv venv -p 3.10 /Users/hugo/github/termcolor/.tox/.pkg/.venv [tox/tox_env/api.py:427]
.pkg: 554 I exit 0 (0.01 seconds) /Users/hugo/github/termcolor> /Users/hugo/.pyenv/versions/pypy3.10-7.3.15/bin/uv venv -p 3.10 /Users/hugo/github/termcolor/.tox/.pkg/.venv pid=86447 [tox/execute/api.py:280]
.pkg: 556 W install_requires> /Users/hugo/.pyenv/versions/pypy3.10-7.3.15/bin/uv pip install hatch-vcs hatchling [tox/tox_env/api.py:427]
Resolved 11 packages in 10ms
Installed 11 packages in 12ms
 + editables==0.5
 + hatch-vcs==0.4.0
 + hatchling==1.21.1
 + packaging==23.2
 + pathspec==0.12.1
 + pluggy==1.4.0
 + setuptools==69.1.0
 + setuptools-scm==8.0.4
 + tomli==2.0.1
 + trove-classifiers==2024.1.31
 + typing-extensions==4.9.0
.pkg: 725 I exit 0 (0.17 seconds) /Users/hugo/github/termcolor> /Users/hugo/.pyenv/versions/pypy3.10-7.3.15/bin/uv pip install hatch-vcs hatchling pid=86448 [tox/execute/api.py:280]
.pkg: 727 W _optional_hooks> python /Users/hugo/.pyenv/versions/pypy3.10-7.3.15/lib/pypy3.10/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
py: 802 E packaging backend failed (code=-5), with FailedToStart: could not start backend
failed to start backend
Traceback (most recent call last):
  File "/Users/hugo/.pyenv/versions/pypy3.10-7.3.15/lib/pypy3.10/site-packages/pyproject_api/_backend.py", line 132, in <module>
    sys.exit(run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/pypy3.10-7.3.15/lib/pypy3.10/site-packages/pyproject_api/_backend.py", line 63, in run
    backend_proxy = BackendProxy(argv[1], None if len(argv) == 2 else argv[2])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/pypy3.10-7.3.15/lib/pypy3.10/site-packages/pyproject_api/_backend.py", line 23, in __init__
    backend = importlib.import_module(self.backend_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hugo/.pyenv/versions/pypy3.10-7.3.15/lib/pypy3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hatchling' [tox/session/cmd/run/single.py:54]
  py: FAIL code -5 (0.38 seconds)
  evaluation failed :( (0.67 seconds)
```

I saw https://github.com/tox-dev/tox-uv/issues/14 which says PyPy isn't supported yet, but this is getting further with `-e py` or `-e pypy3.10`, than that with `-e pypy` or `pypy3`.

**Comment by gaborbernat** [comment]
Can you please update the run output with https://github.com/tox-dev/tox-uv/releases/tag/1.3.0 using `tox -rvvv`. Thanks!

**Comment by hugovk** [comment]
Here we go: https://github.com/hugovk/termcolor/actions/runs/7955657669/job/21714985260

```pytb
.pkg: 2545 W _optional_hooks> python /opt/hostedtoolcache/PyPy/3.10.13/x64/lib/pypy3.10/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
py: 2621 E packaging backend failed (code=-5), with FailedToStart: could not start backend
failed to start backend
Traceback (most recent call last):
  File "/opt/hostedtoolcache/PyPy/3.10.13/x64/lib/pypy3.10/site-packages/pyproject_api/_backend.py", line 132, in <module>
    sys.exit(run(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/PyPy/3.10.13/x64/lib/pypy3.10/site-packages/pyproject_api/_backend.py", line 63, in run
    backend_proxy = BackendProxy(argv[1], None if len(argv) == 2 else argv[2])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/PyPy/3.10.13/x64/lib/pypy3.10/site-packages/pyproject_api/_backend.py", line 23, in __init__
    backend = importlib.import_module(self.backend_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/PyPy/3.10.13/x64/lib/pypy3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hatchling' [tox/session/cmd/run/single.py:54]
  py: FAIL code -5 (0.67 seconds)
  evaluation failed :( (2.15 seconds)

Error: Process completed with exit code 251.
```

**Comment by gaborbernat** [comment]
Here's the important part, seems this is a bug in uv or us, because we create this env `/home/runner/work/termcolor/termcolor/.tox/.pkg/.venv`:

```
.pkg: 2077 W venv> /opt/hostedtoolcache/PyPy/3.10.13/x64/bin/uv venv -p 3.10 -v /home/runner/work/termcolor/termcolor/.tox/.pkg/.venv [tox/tox_env/api.py:427]
 uv_interpreter::python_query::find_requested_python request="3.10", platform=Platform { os: Manylinux { major: 2, minor: 35 }, arch: X86_64 }, cache=Cache { root: "/home/runner/.cache/uv", refresh: None, _temp_dir_drop: None }
      0.002706s   0ms DEBUG uv_interpreter::interpreter Using cached markers for: /opt/hostedtoolcache/PyPy/3.10.13/x64/bin/python3.10
Using Python 3.10.13 interpreter at /opt/hostedtoolcache/PyPy/3.10.13/x64/bin/python3.10
Creating virtualenv at: /home/runner/work/termcolor/termcolor/.tox/.pkg/.venv
.pkg: [20](https://github.com/hugovk/termcolor/actions/runs/7955657669/job/21714985260#step:5:21)93 I exit 0 (0.01 seconds) 
```

Then we're installing hatchling in that, and succeeds:

```/home/runner/work/termcolor/termcolor/.tox/.pkg/.venv pid=1798 [tox/execute/api.py:280]
.pkg: 2098 W install_requires> /opt/hostedtoolcache/PyPy/3.10.13/x64/bin/uv pip install hatch-vcs hatchling -v [tox/tox_env/api.py:427]

Installed 11 packages in 7ms
 + editables==0.5
 + hatch-vcs==0.4.0
 + hatchling==1.21.1
 + packaging==23.2
 + pathspec==0.12.1
 + pluggy==1.4.0
 + setuptools==69.1.0
 + setuptools-scm==8.0.4
 + tomli==2.0.1
 + trove-classifiers==2024.1.31
 + typing-extensions==4.9.0
```

But still missing in the python env when starting:

```
.pkg: 2545 W _optional_hooks> python /opt/hostedtoolcache/PyPy/3.10.13/x64/lib/pypy3.10/site-packages/pyproject_api/_backend.py True hatchling.build [tox/tox_env/api.py:427]
py: 2621 E packaging backend failed (code=-5), with FailedToStart: could not start backend
...
ModuleNotFoundError: No module named 'hatchling' [tox/session/cmd/run/single.py:54]
```

**Comment by edgarrmondragon** [comment]
FWIW I think it's a bug in uv. I'm seeing the same error [using Nox](https://github.com/wntrblm/nox/pull/762#pullrequestreview-1891142309):

<details><summary>Nox output</summary>
<p>

```
nox > Command uv pip install -v 'citric[tests] @ .' failed with exit code 2:
 uv::requirements::from_source source=citric[tests] @ .
    0.003331s DEBUG uv_interpreter::virtual_env Found a virtualenv through VIRTUAL_ENV at: /home/runner/work/citric/citric/.nox/tests-pypy3-10
    0.003447s DEBUG uv_interpreter::interpreter Detecting markers for: /home/runner/work/citric/citric/.nox/tests-pypy3-10/bin/python
    0.074974s DEBUG uv::commands::pip_install Using Python 3.10.13 environment at /home/runner/work/citric/citric/.nox/tests-pypy3-10/bin/python
    0.075370s DEBUG uv_client::registry_client Using registry request timeout of 300s
 uv_client::flat_index::from_entries 
 uv_resolver::resolver::solve 
      0.076430s   0ms DEBUG uv_resolver::resolver Solving with target Python version 3.10.13
   uv_resolver::resolver::choose_version package=root
   uv_resolver::resolver::get_dependencies package=root, version=0a0.dev0
        0.076503s   0ms DEBUG uv_resolver::resolver Adding direct dependency: citric[tests]*
        0.076538s   0ms DEBUG uv_resolver::resolver Adding direct dependency: citric*
   uv_resolver::resolver::choose_version package=citric
        0.076581s   0ms DEBUG uv_resolver::resolver Searching for a compatible version of citric @ file:///home/runner/work/citric/citric (*)
 uv_resolver::resolver::process_request request=Metadata citric @ file:///home/runner/work/citric/citric
   uv_distribution::distribution_database::get_or_build_wheel_metadata dist=citric @ file:///home/runner/work/citric/citric
     uv_distribution::source::build_source_dist_metadata 
          0.077060s   0ms DEBUG uv_distribution::source Preparing metadata for: citric @ file:///home/runner/work/citric/citric
       uv_dispatch::setup_build package_id="citric @ file:///home/runner/work/citric/citric", subdirectory=None
         uv_resolver::resolver::solve 
              0.078573s   0ms DEBUG uv_resolver::resolver Solving with target Python version 3.10.13
           uv_resolver::resolver::choose_version package=root
           uv_resolver::resolver::get_dependencies package=root, version=0a0.dev0
                0.078615s   0ms DEBUG uv_resolver::resolver Adding direct dependency: hatch-vcs*
                0.078627s   0ms DEBUG uv_resolver::resolver Adding direct dependency: hatchling*
           uv_resolver::resolver::choose_version package=hatch-vcs
             uv_resolver::resolver::package_wait package_name=hatch-vcs
         uv_resolver::resolver::process_request request=Versions hatch-vcs
             uv_installer::downloader::get_wheel name=editables==0.5, size=Some(5098), url="https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl"
               uv_distribution::distribution_database::get_or_build_wheel dist=Built(Registry(RegistryBuiltDist { filename: WheelFilename { name: PackageName("editables"), version: "0.5", python_tag: ["py3"], abi_tag: ["none"], platform_tag: ["any"] }, file: File { dist_info_metadata: None, filename: "editables-0.5-py3-none-any.whl", hashes: Hashes { md5: None, sha256: Some("61e5ffa82629e0d8bfe09bc44a07db3c1ab8ed1ce78a6980732870f19b5e7d4c") }, requires_python: Some(VersionSpecifiers([VersionSpecifier { operator: GreaterThanEqual, version: "3.7" }])), size: Some(5098), upload_time_utc_ms: Some(1690[22](https://github.com/edgarrmondragon/citric/actions/runs/7978317614/job/21783180633?pr=1098#step:5:23)3189046), url: AbsoluteUrl("https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl"), yanked: Some(Bool(false)) }, index: Pypi }))
                 uv_client::cached_client::get_serde 
                   uv_client::cached_client::get_cacheable 
                     uv_client::cached_client::read_and_parse_cache file=/home/runner/.cache/uv/wheels-v0/pypi/editables/editables-0.5-py3-none-any.http
                        0.266342s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/bb/0a/203797141ec9727344c7649f6d5f6cf71b89a6c28f8f55d4f18de7a1d352/setuptools-69.1.0-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/bb/0a/203797141ec9727344c7649f6d5f6cf71b89a6c28f8f55d4f18de7a1d352/setuptools-69.1.0-py3-none-any.whl"
                        0.266387s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/3a/bb/40528a09a33845bd7fd75c33b3be7faec3b5c8f15f68a58931da67420fb9/hatchling-1.21.1-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/3a/bb/40528a09a33845bd7fd75c33b3be7faec3b5c8f15f68a58931da67420fb9/hatchling-1.21.1-py3-none-any.whl"
                        0.266415s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a[23](https://github.com/edgarrmondragon/citric/actions/runs/7978317614/job/21783180633?pr=1098#step:5:24)7ff42367d/packaging-23.2-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl"
                        0.266440s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/0e/a3/b9a8b0adfe672bf0df5901707aa929d30a97ee390ba651910186776746d2/setuptools_scm-8.0.4-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/0e/a3/b9a8b0adfe672bf0df5901707aa929d30a97ee390ba651910186776746d2/setuptools_scm-8.0.4-py3-none-any.whl"
                        0.266466s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl"
                        0.266485s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl"
                        0.266510s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/a5/5b/0cc789b59e8cc1bf288b38111d002d8c5917123194d45b29dcdac64723cc/pluggy-1.4.0-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/a5/5b/0cc789b59e8cc1bf288b38111d002d8c5917123194d45b29dcdac64723cc/pluggy-1.4.0-py3-none-any.whl"
                        0.266533s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/6b/4e/599b1d41680dc063166bc8872e96f05967200[24](https://github.com/edgarrmondragon/citric/actions/runs/7978317614/job/21783180633?pr=1098#step:5:25)5a338bd404d669e1ae3fa/trove_classifiers-2024.1.31-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/6b/4e/599b1d41680dc063166bc8872e96f05967200245a338bd404d669e1ae3fa/trove_classifiers-2024.1.31-py3-none-any.whl"
                        0.266576s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a[25](https://github.com/edgarrmondragon/citric/actions/runs/7978317614/job/21783180633?pr=1098#step:5:26)47f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d209[26](https://github.com/edgarrmondragon/citric/actions/runs/7978317614/job/21783180633?pr=1098#step:5:27)a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl"
                        0.266635s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/82/0f/6cbd9976160bc334add63bc2e7a58b1433a31b34b7cda6c5de6dd983d9a7/hatch_vcs-0.4.0-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/82/0f/6cbd9976160bc334add63bc2e7a58b1433a31b34b7cda6c5de6dd983d9a7/hatch_vcs-0.4.0-py3-none-any.whl"
                        0.266668s   0ms DEBUG uv_client::cached_client No cache entry for: https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl
                     uv_client::cached_client::fresh_request url="https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl"
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/setuptools/setuptools-69.1.0-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=setuptools==69.1.0
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/tomli/tomli-2.0.1-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=tomli==2.0.1
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/editables/editables-0.5-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=editables==0.5
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/pluggy/pluggy-1.4.0-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=pluggy==1.4.0
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/trove-classifiers/trove_classifiers-2024.1.31-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=trove-classifiers==2024.1.31
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/hatch-vcs/hatch_vcs-0.4.0-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=hatch-vcs==0.4.0
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/packaging/packaging-23.2-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=packaging==23.2
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/typing-extensions/typing_extensions-4.9.0-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=typing-extensions==4.9.0
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/hatchling/hatchling-1.21.1-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=hatchling==1.21.1
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/setuptools-scm/setuptools_scm-8.0.4-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=setuptools-scm==8.0.4
                     uv_client::cached_client::new_cache file=/home/runner/.cache/uv/wheels-v0/pypi/pathspec/pathspec-0.12.1-py3-none-any.http
                     uv_distribution::distribution_database::download wheel=pathspec==0.12.1
              0.320802s  55ms DEBUG uv_dispatch Installing build requirements: editables==0.5, tomli==2.0.1, trove-classifiers==2024.1.31, hatch-vcs==0.4.0, pluggy==1.4.0, typing-extensions==4.9.0, pathspec==0.12.1, packaging==23.2, setuptools-scm==8.0.4, hatchling==1.21.1, setuptools==69.1.0
           uv_installer::installer::install num_wheels=11
            0.3[29](https://github.com/edgarrmondragon/citric/actions/runs/7978317614/job/21783180633?pr=1098#step:5:30)1[35](https://github.com/edgarrmondragon/citric/actions/runs/7978317614/job/21783180633?pr=1098#step:5:36)s 252ms DEBUG uv_build Calling `hatchling.build.get_requires_for_build_wheel()`
         uv_build::run_python_script script="get_requires_for_build_wheel", python_version=3.10.13
error: Failed to build: citric @ file:///home/runner/work/citric/citric
  Caused by: Failed to build: citric @ file:///home/runner/work/citric/citric
  Caused by: Build backend failed to determine extra requires with `build_wheel()`:
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'hatchling'
---
```

</p>
</details>

**Comment by gaborbernat** [comment]
@edgarrmondragon can you open an issue there and link it from here? Thanks!

**Comment by henryiii** [comment]
Is it related to the extra? There's still missing stuff for handling extras in UV.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon can you open an issue there and link it from here? Thanks!

I think this is the same as https://github.com/astral-sh/uv/issues/1488

**Comment by edgarrmondragon** [comment]
The next version of uv might fix this

**Comment by hugovk** [comment]
Confirming the new uv 0.1.14 works with PyPy for Ubuntu and macOS:

https://github.com/hugovk/termcolor/actions/runs/8145079624

(Windows is another issue.)

Thanks!
